### ISSUE TITLE
contractAgreementId is null

### ISSUE THREAD

**Issue by logicalfarhad** [FraunhoferIOSB/EDC-Extension-for-AAS#13]
Hello there

I was trying to run the postman collection from the example. However, I saw that the contractAgreementId is null, so the transfer request is in an error state. Please see the screenshot. 
![error](https://user-images.githubusercontent.com/2293175/202037408-85e6c968-6d01-4a43-867e-508fde7f548e.png)

Any idea how to solve this? 

Many thanks for considering my request.

Best Regards
Farhad

**Comment by carlos-schmidt** [comment]
Hello Farhad,

thanks for your issue.

Have you provided valid asset/contract IDs in the "Variables" section of the postman collection?

You can find out assetId and contractId for an asset by requesting the selfDescription of a provider EDC (Endpoint: /api/selfDescription).

After that you should be able to get an agreementId out of the request, paste it into the "agreementId" variable of the postman collection and execute the third command.

There is a tutorial for this use-case at https://github.com/FraunhoferIOSB/EDC-Extension-for-AAS/tree/main/example#running-the-example where all the steps are described in more detail

If these steps didn't help you, could you please provide your postman variables and the error log output of the consumer/provider EDCs if there is any?

**Comment by logicalfarhad** [comment]
Hi Carlos 

Thanks for your reply. You are right, I forgot to change the variable's value in the postman. 
It is working perfectly. 

Best 
Farhad
