### ISSUE TITLE
Getting all ASS including Submodels and their Elements

### ISSUE THREAD

**Issue by AnVentura** [FraunhoferIOSB/EDC-Extension-for-AAS#138]
First of all, congratulations on the project.
I have a question, I would like to know if it is possible when sending an Asset Administration shell, to send the entire AAS with submodels and submodel elements included.
I was doing some tests and it seemed to me that what was possible to see on the client side was limited.

I thought it might have been the settings, but in onlySubmodels I set it to false.

I hope you can help me!

Translated with DeepL.com (free version)

**Comment by carlos-schmidt** [comment]
Hello @AnVentura ,

it is only possible to send one of the following at once:
- one submodel including its submodel elements
- one submodel element
- one shell
- one concept description

Sending the entire environment / a shell with its corresponding submodels is currently not possible
