### ISSUE TITLE
Example is not working

### ISSUE THREAD

**Issue by DevBadi** [FraunhoferIOSB/EDC-Extension-for-AAS#21]
I'm working on this [Example](https://github.com/FraunhoferIOSB/EDC-Extension-for-AAS/tree/main/example)
When i run the consumer it is working 
`java -Dedc.fs.config=./example/configurations/consumer.properties -jar ./example/build/libs/dataspace-connector.jar`
but when i run the provider 
`java -Dedc.fs.config=./example/configurations/provider.properties -jar ./example/build/libs/dataspace-connector.jar`
i'm getting this problem 

![image](https://user-images.githubusercontent.com/18467886/224294310-4c29cf51-9484-4e68-91ee-a7a3bf0cc90b.png)

## PS
I tested both localy and using docker and got the same problem

# My idea
I thing the problem has somethiong to do with the last  [merge request](https://github.com/FraunhoferIOSB/EDC-Extension-for-AAS/pull/17)  from  @carlos-schmidt 
`web.http.management.port = 8182 `
`web.http.protocol.port = 8282`
when i change the protocol port to 8585 for example it works, i think the port 8282 is called in the Dataspace-connector.jar file

**Comment by carlos-schmidt** [comment]
Hello DevBadi,

I was not able to reproduce your errors using the commands

`java -Dedc.fs.config=./example/configurations/consumer.properties -jar ./example/build/libs/dataspace-connector.jar`
and
`java -Dedc.fs.config=./example/configurations/provider.properties -jar ./example/build/libs/dataspace-connector.jar`.

Maybe the port 8282 was already in use by another service? The docker provider also binds to port 8282 on your system, so this would be the same error. You could check the port availability by running `Get-Process -Id (Get-NetTCPConnection -LocalPort 8282).OwningProcess` in PowerShell for example.

Nonetheless I have found some errors and outdated requests in the example and have pushed an update (https://github.com/FraunhoferIOSB/EDC-Extension-for-AAS/pull/22), so if you'd like, you can try the example again with the newest commit.

**Comment by DevBadi** [comment]
Hi Carlos,

yes, itnow the provider now is running.
