### ISSUE TITLE
Postman collection has typo or the source is wrong

### ISSUE THREAD

**Issue by miwamasa** [FraunhoferIOSB/EDC-Extension-for-AAS#42]
Executing "1. Execute the request `Client/1. Get dataset for asset` failed.

> Error 404 Not Found

It seems that path "datasets" should be "data" or the source code for  handling this request is wrong.

Anyway, changing to "dataset" just worked fine for me.

> {{consumer}}/api/automated/datasets?providerUrl={{provider-dsp}}&assetId={{asset-id}}

should be

>{{consumer}}/api/automated/**dataset**?providerUrl={{provider-dsp}}&assetId={{asset-id}}

  BreadcrumbsEDC-Extension-for-AAS/example/resources
/aas_edc_extension.postman_collection.json

```
         "name": "1. Get datasets for asset",
          "request": {
            "method": "GET",
            "header": [],
            "url": {
              "raw": "{{consumer}}/api/automated/datasets?providerUrl={{provider-dsp}}&assetId={{asset-id}}",
              "host": [
                "{{consumer}}"
              ],
```

**Comment by carlos-schmidt** [comment]
Thanks for bringing this up!
