### ISSUE TITLE
'Iri' in idType seems not  aligned with AAS shcema

### ISSUE THREAD

**Issue by miwamasa** [FraunhoferIOSB/EDC-Extension-for-AAS#57]
We have some error to exchange json via consumer/produder protocol.
We found that your implementation requires only 'Iri' in the idType in aas json.

We have checked your example demoAAS.json, 
>   "keys": [
              {
                "idType": "Iri",
                "type": "GlobalReference",
                "value": "0173-1#02-AAO677#002"
              }
            ]
          },

BUT it should be 'IRI'  in accordance with   the DataTypeIec61360 in the aas scheme 

![image](https://github.com/FraunhoferIOSB/EDC-Extension-for-AAS/assets/730771/ad239517-bf78-4008-bff2-b118e073b7e3)

https://github.com/admin-shell-io/aas-specs/blob/master/schemas/json/aas.json

it seems 'IRI' instead of 'Iri' is official, 

I wonder if other type like "IRDI" are also accepted as json data.

**Comment by fvolz** [comment]
Hi, the idType is handled by the AAS Java Model https://github.com/eclipse-aas4j/aas4j 
In the next pull request https://github.com/FraunhoferIOSB/EDC-Extension-for-AAS/pull/44 we will update the AAS4J version and try to include the correct "IRI" in AAS4J
The Java Model should be able to handle all idTypes.
